sudo: required #is required to use docker service in travis
language: go
services:
  - docker
install: skip
before_script:
  - go get github.com/golang/dep/cmd/dep
  - dep ensure -vendor-only
script:
  - go vet  # go vet is the official Go static analyzer
  - go test -v -race  # Run all the tests with the race detector enabled
  - docker build -t godocker .
after_success:
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --no-include-email --region ap-northeast-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker tag godocker:latest
  - docker push
